---
# tasks file for lamp

- name: Install Lamp services
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: latest

- name: Start service httpd and enabled
  ansible.builtin.service:
    name: "{{ services[0] }}"
    state: started
    enabled: yes

- name: Start service Mariadb and enabled
  ansible.builtin.service:
    name: "{{ services[1] }}"
    state: started
    enabled: yes

- name: Permanently enable https service
  ansible.posix.firewalld:
    service: http 
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Website Deployment
  ansible.builtin.copy:
    src: /home/ansible/lamp/lamp/files/web/
    dest: /var/www/html/
  ignore_errors: True



